// 完整版菜单比较多，将 rank 抽离出来，在此方便维护
// Phiên bản đầy đủ có nhiều menu hơn, và thứ hạng được trích ra để thuận tiện cho việc bảo trì tại đây.
// Nền tảng quy định rằng chỉ thứ hạng của tuyến đường về nhà mới có thể là 0, do đó phần phụ trợ cần bắt đầu từ khác 0 khi trả về thứ hạng.
// 平台规定只有 home 路由的 rank 才能为 0 ，所以后端在返回 rank 的时候需要从非 0 开始
const home = 0,
  checkin = 1,
  task = 2,
  project = 3,
  vueflow = 4,
  ganttastic = 5,
  components = 6,
  able = 7,
  table = 8,
  form = 9,
  list = 10,
  result = 11,
  error = 12,
  frame = 13,
  nested = 14,
  permission = 15,
  system = 16,
  monitor = 17,
  tabs = 18,
  about = 19,
  editor = 20,
  flowchart = 21,
  formdesign = 22,
  board = 23,
  ppt = 24,
  mind = 25,
  guide = 26,
  menuoverflow = 27;
export {
  home,
  checkin,
  task,
  project,
  vueflow,
  ganttastic,
  components,
  able,
  table,
  form,
  list,
  result,
  error,
  frame,
  nested,
  permission,
  system,
  monitor,
  tabs,
  about,
  editor,
  flowchart,
  formdesign,
  board,
  ppt,
  mind,
  guide,
  menuoverflow
};
